version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
      - ./initdb/:/docker-entrypoint-initdb.d/
    networks:
      - replica-set
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - replica-set
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - replica-set
    ports:
      - 27023:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - replica-set

  app:
    build: ./app
    expose:
      - 5000
    ports:
      - "5100:5000"
    networks:
      - replica-set
    labels:
     # Create a middleware named `foo-add-prefix`
      - "traefik.http.middlewares.foo-add-prefix.addprefix.prefix=/staj"
    # Apply the middleware named `foo-add-prefix` to the router named `router1`
      - "traefik.http.routers.router1.middlewares=foo-add-prefix@docker"
      - traefik.http.routers.flask.rule=Host(`kartaca.localhost`) 
      - traefik.http.middlewares.test-replacepathregex.replacepathregex.regex=^/staj/(.*)
      - traefik.http.middlewares.test-replacepathregex.replacepathregex.replacement=/pythonapp/$$1
  


    
networks:
 replica-set:
    driver: bridge