global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitoring'
  
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']





